name: "[both-debian] Force Build and Push"
on:
  workflow_dispatch:

env:
  #PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  PLATFORMS: "linux/amd64,linux/arm64"
  #PLATFORMS: "linux/amd64"
  TAG: "1.7.1"
  latest: "true"

jobs:
  server-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build without latest
      - name: Build and push - server [debian]
        if: ${{ env.latest == 'false' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          #   tiltedevolution-server
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     server-debian
          #     server-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-${{ env.TAG }}-debian
          build-args: |
            BRANCH=v${{ env.TAG }}

      - name: Build and push - pterodactyl [debian]
        if: ${{ env.latest == 'false' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.pterodactyl
          platforms: ${{ env.PLATFORMS }}
          #   tiltedevolution-pterodactyl
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     pterodactyl-debian
          #     pterodactyl-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
          build-args: |
            VERSION=${{ env.TAG }}

      # Build with latest
      - name: Build and push - server [debian]
        if: ${{ env.latest == 'true' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          #   tiltedevolution-server
          #     latest-debian
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     server-debian
          #     server-latest-debian
          #     server-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-${{ env.TAG }}-debian
          build-args: |
            BRANCH=v${{ env.TAG }}

      - name: Build and push - pterodactyl [debian]
        if: ${{ env.latest == 'true' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.pterodactyl
          platforms: ${{ env.PLATFORMS }}
          #   tiltedevolution-pterodactyl
          #     latest-debian
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     pterodactyl-debian
          #     pterodactyl-latest-debian
          #     pterodactyl-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
          build-args: |
            VERSION=${{ env.TAG }}
