name: "[server, pterodactyl] Auto Build and Push"
# run every two hours to check for updates
on:
#  schedule:
#  - cron: "0 */2 * * *"
  workflow_dispatch:

env:
  #ALPINE_PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  #ALPINE_PLATFORMS: "linux/amd64,linux/arm64"
  ALPINE_PLATFORMS: "linux/amd64"
  DEBIAN_PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tags
        run: |
          echo "GIT_TAG=$(curl -sL https://api.github.com/repos/tiltedphoques/TiltedEvolution/tags | jq -r '.[].name' | sort -r | head -n 1 | sed 's/v//')" >> $GITHUB_ENV
          echo "GIT_TAG_V=$(curl -sL https://api.github.com/repos/tiltedphoques/TiltedEvolution/tags | jq -r '.[].name' | sort -r | head -n 1)" >> $GITHUB_ENV
          echo "DOCKER_TAG=$(curl -sL https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server/tags | jq -r '.results[].name' | grep -v "latest" | sort -r | head -n 1)" >> $GITHUB_ENV

      - name: Output latest Tags
        run: |
          echo "Git: ${{ env.GIT_TAG }}"
          echo "Git: ${{ env.GIT_TAG_V }}"
          echo "Docker: ${{ env.DOCKER_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Alpine - server
      - name: Build and push - server
        uses: docker/build-push-action@v6
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          push: true
          file: alpine/Dockerfile.server
          platforms: ${{ env.ALPINE_PLATFORMS }}
          #   tiltedevolution-server
          #     latest
          #     {{ TAG }}
          #   tiltedevolution
          #     server
          #     server-latest
          #     server-{{ TAG }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:${{ env.GIT_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-${{ env.GIT_TAG }}
          build-args: |
            BRANCH=${{ env.GIT_TAG_V }}

      # Alpine - pterodactyl
      - name: Build and push - pterodactyl
        uses: docker/build-push-action@v6
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          push: true
          file: alpine/Dockerfile.pterodactyl
          platforms: ${{ env.ALPINE_PLATFORMS }}
          #   tiltedevolution-pterodactyl
          #     latest
          #     {{ TAG }}
          #   tiltedevolution
          #     pterodactyl
          #     pterodactyl-latest
          #     pterodactyl-{{ TAG }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:${{ env.GIT_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-${{ env.GIT_TAG }}
          build-args: |
            VERSION=${{ env.GIT_TAG }}

      # Debian - server
      - name: Build and push - server [debian]
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.server
          platforms: ${{ env.DEBIAN_PLATFORMS }}
          #   tiltedevolution-server
          #     latest-debian
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     server-debian
          #     server-latest-debian
          #     server-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-${{ env.TAG }}-debian
          build-args: |
            BRANCH=v${{ env.GIT_TAG_V }}

      # Debian - pterodactyl
      - name: Build and push - pterodactyl [debian]
        uses: docker/build-push-action@v6
        with:
          push: true
          file: debian/Dockerfile.pterodactyl
          platforms: ${{ env.DEBIAN_PLATFORMS }}
          #   tiltedevolution-pterodactyl
          #     latest-debian
          #     {{ TAG }}-debian
          #   tiltedevolution
          #     pterodactyl-debian
          #     pterodactyl-latest-debian
          #     pterodactyl-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-${{ env.TAG }}-debian
          build-args: |
            VERSION=${{ env.GIT_TAG }}
